version: "2"

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: ^examples/

linters:
  disable:
    - all
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
