run:
  timeout: 5m
  skip-dirs:
    - examples

issues:
  exclude-rules:
    - path: examples/
      linters:
        - typecheck

linters:
  disable:
    - typecheck # Already covered by go vet
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
