// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package enforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfPolicyKey struct {
	CgroupId  uint64
	Ip        uint32
	Port      uint16
	Protocol  uint8
	Direction uint8
}

type bpfPolicyValue struct {
	Action  uint8
	Padding [3]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	FilterEgress            *ebpf.ProgramSpec `ebpf:"filter_egress"`
	FilterEgressPermissive  *ebpf.ProgramSpec `ebpf:"filter_egress_permissive"`
	FilterIngress           *ebpf.ProgramSpec `ebpf:"filter_ingress"`
	FilterIngressPermissive *ebpf.ProgramSpec `ebpf:"filter_ingress_permissive"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FlowEvents *ebpf.MapSpec `ebpf:"flow_events"`
	PolicyMap  *ebpf.MapSpec `ebpf:"policy_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FlowEvents *ebpf.Map `ebpf:"flow_events"`
	PolicyMap  *ebpf.Map `ebpf:"policy_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FlowEvents,
		m.PolicyMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	FilterEgress            *ebpf.Program `ebpf:"filter_egress"`
	FilterEgressPermissive  *ebpf.Program `ebpf:"filter_egress_permissive"`
	FilterIngress           *ebpf.Program `ebpf:"filter_ingress"`
	FilterIngressPermissive *ebpf.Program `ebpf:"filter_ingress_permissive"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.FilterEgress,
		p.FilterEgressPermissive,
		p.FilterIngress,
		p.FilterIngressPermissive,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
