// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/ztap/api/v1/api.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *WhoAmIResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WhoAmIResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WhoAmIResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid           int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *StatusResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *StatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StatusResponse) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type EnforcementStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Platform          string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	EbpfActive        bool                   `protobuf:"varint,2,opt,name=ebpf_active,json=ebpfActive,proto3" json:"ebpf_active,omitempty"`
	FlowEventsPinPath string                 `protobuf:"bytes,3,opt,name=flow_events_pin_path,json=flowEventsPinPath,proto3" json:"flow_events_pin_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnforcementStatusResponse) Reset() {
	*x = EnforcementStatusResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStatusResponse) ProtoMessage() {}

func (x *EnforcementStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStatusResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnforcementStatusResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnforcementStatusResponse) GetEbpfActive() bool {
	if x != nil {
		return x.EbpfActive
	}
	return false
}

func (x *EnforcementStatusResponse) GetFlowEventsPinPath() string {
	if x != nil {
		return x.FlowEventsPinPath
	}
	return ""
}

type EnforcementStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyYaml    string                 `protobuf:"bytes,1,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	PolicyName    string                 `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Cgroup        string                 `protobuf:"bytes,3,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	BpfObject     string                 `protobuf:"bytes,4,opt,name=bpf_object,json=bpfObject,proto3" json:"bpf_object,omitempty"`
	DebugEbpf     bool                   `protobuf:"varint,5,opt,name=debug_ebpf,json=debugEbpf,proto3" json:"debug_ebpf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStartRequest) Reset() {
	*x = EnforcementStartRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStartRequest) ProtoMessage() {}

func (x *EnforcementStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStartRequest.ProtoReflect.Descriptor instead.
func (*EnforcementStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *EnforcementStartRequest) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

func (x *EnforcementStartRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *EnforcementStartRequest) GetCgroup() string {
	if x != nil {
		return x.Cgroup
	}
	return ""
}

func (x *EnforcementStartRequest) GetBpfObject() string {
	if x != nil {
		return x.BpfObject
	}
	return ""
}

func (x *EnforcementStartRequest) GetDebugEbpf() bool {
	if x != nil {
		return x.DebugEbpf
	}
	return false
}

type EnforcementStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enforced      bool                   `protobuf:"varint,1,opt,name=enforced,proto3" json:"enforced,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStartResponse) Reset() {
	*x = EnforcementStartResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStartResponse) ProtoMessage() {}

func (x *EnforcementStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStartResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnforcementStartResponse) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

func (x *EnforcementStartResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type EnforcementStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStopResponse) Reset() {
	*x = EnforcementStopResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStopResponse) ProtoMessage() {}

func (x *EnforcementStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStopResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *EnforcementStopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type FlowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp        string                 `protobuf:"bytes,3,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *FlowEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FlowEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *FlowEvent) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *FlowEvent) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *FlowEvent) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *FlowEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FlowEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_proto_ztap_api_v1_api_proto protoreflect.FileDescriptor

const file_proto_ztap_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ztap/api/v1/api.proto\x12\vztap.api.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x90\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"{\n" +
	"\x0eWhoAmIResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"z\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"\x89\x01\n" +
	"\x19EnforcementStatusResponse\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vebpf_active\x18\x02 \x01(\bR\n" +
	"ebpfActive\x12/\n" +
	"\x14flow_events_pin_path\x18\x03 \x01(\tR\x11flowEventsPinPath\"\xb1\x01\n" +
	"\x17EnforcementStartRequest\x12\x1f\n" +
	"\vpolicy_yaml\x18\x01 \x01(\tR\n" +
	"policyYaml\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\x12\x16\n" +
	"\x06cgroup\x18\x03 \x01(\tR\x06cgroup\x12\x1d\n" +
	"\n" +
	"bpf_object\x18\x04 \x01(\tR\tbpfObject\x12\x1d\n" +
	"\n" +
	"debug_ebpf\x18\x05 \x01(\bR\tdebugEbpf\"R\n" +
	"\x18EnforcementStartResponse\x12\x1a\n" +
	"\benforced\x18\x01 \x01(\bR\benforced\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"3\n" +
	"\x17EnforcementStopResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\x8b\x02\n" +
	"\tFlowEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\x03 \x01(\tR\x06destIp\x12\x1f\n" +
	"\vsource_port\x18\x04 \x01(\rR\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action2\x8c\x01\n" +
	"\vAuthService\x12>\n" +
	"\x05Login\x12\x19.ztap.api.v1.LoginRequest\x1a\x1a.ztap.api.v1.LoginResponse\x12=\n" +
	"\x06WhoAmI\x12\x16.google.protobuf.Empty\x1a\x1b.ztap.api.v1.WhoAmIResponse2Q\n" +
	"\rStatusService\x12@\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1b.ztap.api.v1.StatusResponse2\xfd\x01\n" +
	"\x12EnforcementService\x12K\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a&.ztap.api.v1.EnforcementStatusResponse\x12T\n" +
	"\x05Start\x12$.ztap.api.v1.EnforcementStartRequest\x1a%.ztap.api.v1.EnforcementStartResponse\x12D\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a$.ztap.api.v1.EnforcementStopResponse2J\n" +
	"\fFlowsService\x12:\n" +
	"\x06Stream\x12\x16.google.protobuf.Empty\x1a\x16.ztap.api.v1.FlowEvent0\x01B\x1eZ\x1cztap/proto/ztap/api/v1;apiv1b\x06proto3"

var (
	file_proto_ztap_api_v1_api_proto_rawDescOnce sync.Once
	file_proto_ztap_api_v1_api_proto_rawDescData []byte
)

func file_proto_ztap_api_v1_api_proto_rawDescGZIP() []byte {
	file_proto_ztap_api_v1_api_proto_rawDescOnce.Do(func() {
		file_proto_ztap_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ztap_api_v1_api_proto_rawDesc), len(file_proto_ztap_api_v1_api_proto_rawDesc)))
	})
	return file_proto_ztap_api_v1_api_proto_rawDescData
}

var file_proto_ztap_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ztap_api_v1_api_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: ztap.api.v1.LoginRequest
	(*LoginResponse)(nil),             // 1: ztap.api.v1.LoginResponse
	(*WhoAmIResponse)(nil),            // 2: ztap.api.v1.WhoAmIResponse
	(*StatusResponse)(nil),            // 3: ztap.api.v1.StatusResponse
	(*EnforcementStatusResponse)(nil), // 4: ztap.api.v1.EnforcementStatusResponse
	(*EnforcementStartRequest)(nil),   // 5: ztap.api.v1.EnforcementStartRequest
	(*EnforcementStartResponse)(nil),  // 6: ztap.api.v1.EnforcementStartResponse
	(*EnforcementStopResponse)(nil),   // 7: ztap.api.v1.EnforcementStopResponse
	(*FlowEvent)(nil),                 // 8: ztap.api.v1.FlowEvent
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_proto_ztap_api_v1_api_proto_depIdxs = []int32{
	9,  // 0: ztap.api.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: ztap.api.v1.WhoAmIResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 2: ztap.api.v1.FlowEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: ztap.api.v1.AuthService.Login:input_type -> ztap.api.v1.LoginRequest
	10, // 4: ztap.api.v1.AuthService.WhoAmI:input_type -> google.protobuf.Empty
	10, // 5: ztap.api.v1.StatusService.GetStatus:input_type -> google.protobuf.Empty
	10, // 6: ztap.api.v1.EnforcementService.GetStatus:input_type -> google.protobuf.Empty
	5,  // 7: ztap.api.v1.EnforcementService.Start:input_type -> ztap.api.v1.EnforcementStartRequest
	10, // 8: ztap.api.v1.EnforcementService.Stop:input_type -> google.protobuf.Empty
	10, // 9: ztap.api.v1.FlowsService.Stream:input_type -> google.protobuf.Empty
	1,  // 10: ztap.api.v1.AuthService.Login:output_type -> ztap.api.v1.LoginResponse
	2,  // 11: ztap.api.v1.AuthService.WhoAmI:output_type -> ztap.api.v1.WhoAmIResponse
	3,  // 12: ztap.api.v1.StatusService.GetStatus:output_type -> ztap.api.v1.StatusResponse
	4,  // 13: ztap.api.v1.EnforcementService.GetStatus:output_type -> ztap.api.v1.EnforcementStatusResponse
	6,  // 14: ztap.api.v1.EnforcementService.Start:output_type -> ztap.api.v1.EnforcementStartResponse
	7,  // 15: ztap.api.v1.EnforcementService.Stop:output_type -> ztap.api.v1.EnforcementStopResponse
	8,  // 16: ztap.api.v1.FlowsService.Stream:output_type -> ztap.api.v1.FlowEvent
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ztap_api_v1_api_proto_init() }
func file_proto_ztap_api_v1_api_proto_init() {
	if File_proto_ztap_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ztap_api_v1_api_proto_rawDesc), len(file_proto_ztap_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_ztap_api_v1_api_proto_goTypes,
		DependencyIndexes: file_proto_ztap_api_v1_api_proto_depIdxs,
		MessageInfos:      file_proto_ztap_api_v1_api_proto_msgTypes,
	}.Build()
	File_proto_ztap_api_v1_api_proto = out.File
	file_proto_ztap_api_v1_api_proto_goTypes = nil
	file_proto_ztap_api_v1_api_proto_depIdxs = nil
}
