// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/ztap/api/v1/api.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *WhoAmIResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WhoAmIResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WhoAmIResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid           int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *StatusResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *StatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StatusResponse) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type EnforcementStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Platform          string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	EbpfActive        bool                   `protobuf:"varint,2,opt,name=ebpf_active,json=ebpfActive,proto3" json:"ebpf_active,omitempty"`
	FlowEventsPinPath string                 `protobuf:"bytes,3,opt,name=flow_events_pin_path,json=flowEventsPinPath,proto3" json:"flow_events_pin_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnforcementStatusResponse) Reset() {
	*x = EnforcementStatusResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStatusResponse) ProtoMessage() {}

func (x *EnforcementStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStatusResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnforcementStatusResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnforcementStatusResponse) GetEbpfActive() bool {
	if x != nil {
		return x.EbpfActive
	}
	return false
}

func (x *EnforcementStatusResponse) GetFlowEventsPinPath() string {
	if x != nil {
		return x.FlowEventsPinPath
	}
	return ""
}

type EnforcementStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyYaml    string                 `protobuf:"bytes,1,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	PolicyName    string                 `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Cgroup        string                 `protobuf:"bytes,3,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	BpfObject     string                 `protobuf:"bytes,4,opt,name=bpf_object,json=bpfObject,proto3" json:"bpf_object,omitempty"`
	DebugEbpf     bool                   `protobuf:"varint,5,opt,name=debug_ebpf,json=debugEbpf,proto3" json:"debug_ebpf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStartRequest) Reset() {
	*x = EnforcementStartRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStartRequest) ProtoMessage() {}

func (x *EnforcementStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStartRequest.ProtoReflect.Descriptor instead.
func (*EnforcementStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *EnforcementStartRequest) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

func (x *EnforcementStartRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *EnforcementStartRequest) GetCgroup() string {
	if x != nil {
		return x.Cgroup
	}
	return ""
}

func (x *EnforcementStartRequest) GetBpfObject() string {
	if x != nil {
		return x.BpfObject
	}
	return ""
}

func (x *EnforcementStartRequest) GetDebugEbpf() bool {
	if x != nil {
		return x.DebugEbpf
	}
	return false
}

type EnforcementStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enforced      bool                   `protobuf:"varint,1,opt,name=enforced,proto3" json:"enforced,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStartResponse) Reset() {
	*x = EnforcementStartResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStartResponse) ProtoMessage() {}

func (x *EnforcementStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStartResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnforcementStartResponse) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

func (x *EnforcementStartResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type EnforcementStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStopResponse) Reset() {
	*x = EnforcementStopResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStopResponse) ProtoMessage() {}

func (x *EnforcementStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStopResponse.ProtoReflect.Descriptor instead.
func (*EnforcementStopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *EnforcementStopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type FlowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp        string                 `protobuf:"bytes,3,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *FlowEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FlowEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *FlowEvent) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *FlowEvent) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *FlowEvent) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *FlowEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FlowEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PolicySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySummary) Reset() {
	*x = PolicySummary{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySummary) ProtoMessage() {}

func (x *PolicySummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySummary.ProtoReflect.Descriptor instead.
func (*PolicySummary) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *PolicySummary) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PolicySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicySummary) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicySummary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PolicySummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PolicyYaml    string                 `protobuf:"bytes,6,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *Policy) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Policy) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Policy) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

type PolicyRevision struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Tenant                 string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version                int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Source                 string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Reason                 string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Deleted                bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	RollbackFromVersion    int64                  `protobuf:"varint,8,opt,name=rollback_from_version,json=rollbackFromVersion,proto3" json:"rollback_from_version,omitempty"`
	HasRollbackFromVersion bool                   `protobuf:"varint,9,opt,name=has_rollback_from_version,json=hasRollbackFromVersion,proto3" json:"has_rollback_from_version,omitempty"`
	PolicyYaml             string                 `protobuf:"bytes,10,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PolicyRevision) Reset() {
	*x = PolicyRevision{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRevision) ProtoMessage() {}

func (x *PolicyRevision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRevision.ProtoReflect.Descriptor instead.
func (*PolicyRevision) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyRevision) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PolicyRevision) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyRevision) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyRevision) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PolicyRevision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PolicyRevision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyRevision) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *PolicyRevision) GetRollbackFromVersion() int64 {
	if x != nil {
		return x.RollbackFromVersion
	}
	return 0
}

func (x *PolicyRevision) GetHasRollbackFromVersion() bool {
	if x != nil {
		return x.HasRollbackFromVersion
	}
	return false
}

func (x *PolicyRevision) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListPoliciesRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicySummary       `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *ListPoliciesResponse) GetPolicies() []*PolicySummary {
	if x != nil {
		return x.Policies
	}
	return nil
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetPolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type PutPolicyRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tenant             string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PolicyYaml         string                 `protobuf:"bytes,3,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpectedVersion    int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	HasExpectedVersion bool                   `protobuf:"varint,6,opt,name=has_expected_version,json=hasExpectedVersion,proto3" json:"has_expected_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PutPolicyRequest) Reset() {
	*x = PutPolicyRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPolicyRequest) ProtoMessage() {}

func (x *PutPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPolicyRequest.ProtoReflect.Descriptor instead.
func (*PutPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{16}
}

func (x *PutPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PutPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutPolicyRequest) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

func (x *PutPolicyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PutPolicyRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *PutPolicyRequest) GetHasExpectedVersion() bool {
	if x != nil {
		return x.HasExpectedVersion
	}
	return false
}

type PutPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPolicyResponse) Reset() {
	*x = PutPolicyResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPolicyResponse) ProtoMessage() {}

func (x *PutPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPolicyResponse.ProtoReflect.Descriptor instead.
func (*PutPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{17}
}

func (x *PutPolicyResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DeletePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeletePolicyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePolicyResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeletePolicyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListPolicyRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeYaml   bool                   `protobuf:"varint,4,opt,name=include_yaml,json=includeYaml,proto3" json:"include_yaml,omitempty"`
	HasLimit      bool                   `protobuf:"varint,5,opt,name=has_limit,json=hasLimit,proto3" json:"has_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPolicyRevisionsRequest) Reset() {
	*x = ListPolicyRevisionsRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyRevisionsRequest) ProtoMessage() {}

func (x *ListPolicyRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyRevisionsRequest.ProtoReflect.Descriptor instead.
func (*ListPolicyRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListPolicyRevisionsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListPolicyRevisionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPolicyRevisionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPolicyRevisionsRequest) GetIncludeYaml() bool {
	if x != nil {
		return x.IncludeYaml
	}
	return false
}

func (x *ListPolicyRevisionsRequest) GetHasLimit() bool {
	if x != nil {
		return x.HasLimit
	}
	return false
}

type ListPolicyRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*PolicyRevision      `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPolicyRevisionsResponse) Reset() {
	*x = ListPolicyRevisionsResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyRevisionsResponse) ProtoMessage() {}

func (x *ListPolicyRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListPolicyRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{21}
}

func (x *ListPolicyRevisionsResponse) GetRevisions() []*PolicyRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type GetPolicyRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRevisionRequest) Reset() {
	*x = GetPolicyRevisionRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRevisionRequest) ProtoMessage() {}

func (x *GetPolicyRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRevisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetPolicyRevisionRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetPolicyRevisionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPolicyRevisionRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetPolicyRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *PolicyRevision        `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRevisionResponse) Reset() {
	*x = GetPolicyRevisionResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRevisionResponse) ProtoMessage() {}

func (x *GetPolicyRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyRevisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{23}
}

func (x *GetPolicyRevisionResponse) GetRevision() *PolicyRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type RollbackPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ToVersion     int64                  `protobuf:"varint,3,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPolicyRequest) Reset() {
	*x = RollbackPolicyRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPolicyRequest) ProtoMessage() {}

func (x *RollbackPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPolicyRequest.ProtoReflect.Descriptor instead.
func (*RollbackPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{24}
}

func (x *RollbackPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RollbackPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RollbackPolicyRequest) GetToVersion() int64 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

func (x *RollbackPolicyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RollbackPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPolicyResponse) Reset() {
	*x = RollbackPolicyResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPolicyResponse) ProtoMessage() {}

func (x *RollbackPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPolicyResponse.ProtoReflect.Descriptor instead.
func (*RollbackPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{25}
}

func (x *RollbackPolicyResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{26}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{27}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{29}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{30}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	HasRole       bool                   `protobuf:"varint,3,opt,name=has_role,json=hasRole,proto3" json:"has_role,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HasEnabled    bool                   `protobuf:"varint,5,opt,name=has_enabled,json=hasEnabled,proto3" json:"has_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserRequest) GetHasRole() bool {
	if x != nil {
		return x.HasRole
	}
	return false
}

func (x *UpdateUserRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateUserRequest) GetHasEnabled() bool {
	if x != nil {
		return x.HasEnabled
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SetUserPasswordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	NewPassword    string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	OldPassword    string                 `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	HasOldPassword bool                   `protobuf:"varint,4,opt,name=has_old_password,json=hasOldPassword,proto3" json:"has_old_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetUserPasswordRequest) Reset() {
	*x = SetUserPasswordRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordRequest) ProtoMessage() {}

func (x *SetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{33}
}

func (x *SetUserPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *SetUserPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *SetUserPasswordRequest) GetHasOldPassword() bool {
	if x != nil {
		return x.HasOldPassword
	}
	return false
}

type SetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordResponse) Reset() {
	*x = SetUserPasswordResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordResponse) ProtoMessage() {}

func (x *SetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{34}
}

func (x *SetUserPasswordResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteUserResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ClusterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterNode) Reset() {
	*x = ClusterNode{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterNode) ProtoMessage() {}

func (x *ClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterNode.ProtoReflect.Descriptor instead.
func (*ClusterNode) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{37}
}

func (x *ClusterNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClusterNode) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterNode) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ClusterNode) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *ClusterNode) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ClusterNode) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ClusterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        *ClusterNode           `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Nodes         []*ClusterNode         `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,5,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{38}
}

func (x *ClusterStatus) GetLeader() *ClusterNode {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *ClusterStatus) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *ClusterStatus) GetNodes() []*ClusterNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ClusterStatus) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

type GetClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ClusterStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatusResponse) Reset() {
	*x = GetClusterStatusResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusResponse) ProtoMessage() {}

func (x *GetClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{39}
}

func (x *GetClusterStatusResponse) GetStatus() *ClusterStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ClusterNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{40}
}

func (x *ListNodesResponse) GetNodes() []*ClusterNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *ClusterNode           `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{41}
}

func (x *RegisterNodeRequest) GetNode() *ClusterNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *ClusterNode           `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{42}
}

func (x *RegisterNodeResponse) GetNode() *ClusterNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeregisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterNodeRequest) Reset() {
	*x = DeregisterNodeRequest{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeRequest) ProtoMessage() {}

func (x *DeregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*DeregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{43}
}

func (x *DeregisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeregisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterNodeResponse) Reset() {
	*x = DeregisterNodeResponse{}
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterNodeResponse) ProtoMessage() {}

func (x *DeregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ztap_api_v1_api_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*DeregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ztap_api_v1_api_proto_rawDescGZIP(), []int{44}
}

func (x *DeregisterNodeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_proto_ztap_api_v1_api_proto protoreflect.FileDescriptor

const file_proto_ztap_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ztap/api/v1/api.proto\x12\vztap.api.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x90\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"{\n" +
	"\x0eWhoAmIResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"z\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"\x89\x01\n" +
	"\x19EnforcementStatusResponse\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vebpf_active\x18\x02 \x01(\bR\n" +
	"ebpfActive\x12/\n" +
	"\x14flow_events_pin_path\x18\x03 \x01(\tR\x11flowEventsPinPath\"\xb1\x01\n" +
	"\x17EnforcementStartRequest\x12\x1f\n" +
	"\vpolicy_yaml\x18\x01 \x01(\tR\n" +
	"policyYaml\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\x12\x16\n" +
	"\x06cgroup\x18\x03 \x01(\tR\x06cgroup\x12\x1d\n" +
	"\n" +
	"bpf_object\x18\x04 \x01(\tR\tbpfObject\x12\x1d\n" +
	"\n" +
	"debug_ebpf\x18\x05 \x01(\bR\tdebugEbpf\"R\n" +
	"\x18EnforcementStartResponse\x12\x1a\n" +
	"\benforced\x18\x01 \x01(\bR\benforced\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"3\n" +
	"\x17EnforcementStopResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\x8b\x02\n" +
	"\tFlowEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\x03 \x01(\tR\x06destIp\x12\x1f\n" +
	"\vsource_port\x18\x04 \x01(\rR\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\"\xa8\x01\n" +
	"\rPolicySummary\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x01\n" +
	"\x06Policy\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vpolicy_yaml\x18\x06 \x01(\tR\n" +
	"policyYaml\"\xeb\x02\n" +
	"\x0ePolicyRevision\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted\x122\n" +
	"\x15rollback_from_version\x18\b \x01(\x03R\x13rollbackFromVersion\x129\n" +
	"\x19has_rollback_from_version\x18\t \x01(\bR\x16hasRollbackFromVersion\x12\x1f\n" +
	"\vpolicy_yaml\x18\n" +
	" \x01(\tR\n" +
	"policyYaml\"-\n" +
	"\x13ListPoliciesRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"N\n" +
	"\x14ListPoliciesResponse\x126\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1a.ztap.api.v1.PolicySummaryR\bpolicies\">\n" +
	"\x10GetPolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x11GetPolicyResponse\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.ztap.api.v1.PolicyR\x06policy\"\xd4\x01\n" +
	"\x10PutPolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vpolicy_yaml\x18\x03 \x01(\tR\n" +
	"policyYaml\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\x120\n" +
	"\x14has_expected_version\x18\x06 \x01(\bR\x12hasExpectedVersion\"-\n" +
	"\x11PutPolicyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"Y\n" +
	"\x13DeletePolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"J\n" +
	"\x14DeletePolicyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\x9e\x01\n" +
	"\x1aListPolicyRevisionsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12!\n" +
	"\finclude_yaml\x18\x04 \x01(\bR\vincludeYaml\x12\x1b\n" +
	"\thas_limit\x18\x05 \x01(\bR\bhasLimit\"X\n" +
	"\x1bListPolicyRevisionsResponse\x129\n" +
	"\trevisions\x18\x01 \x03(\v2\x1b.ztap.api.v1.PolicyRevisionR\trevisions\"`\n" +
	"\x18GetPolicyRevisionRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"T\n" +
	"\x19GetPolicyRevisionResponse\x127\n" +
	"\brevision\x18\x01 \x01(\v2\x1b.ztap.api.v1.PolicyRevisionR\brevision\"z\n" +
	"\x15RollbackPolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"to_version\x18\x03 \x01(\x03R\ttoVersion\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"2\n" +
	"\x16RollbackPolicyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\xc6\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\"<\n" +
	"\x11ListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.ztap.api.v1.UserR\x05users\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"_\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\";\n" +
	"\x12CreateUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.ztap.api.v1.UserR\x04user\"\x99\x01\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x19\n" +
	"\bhas_role\x18\x03 \x01(\bR\ahasRole\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1f\n" +
	"\vhas_enabled\x18\x05 \x01(\bR\n" +
	"hasEnabled\";\n" +
	"\x12UpdateUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.ztap.api.v1.UserR\x04user\"\xa4\x01\n" +
	"\x16SetUserPasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12!\n" +
	"\fold_password\x18\x03 \x01(\tR\voldPassword\x12(\n" +
	"\x10has_old_password\x18\x04 \x01(\bR\x0ehasOldPassword\"3\n" +
	"\x17SetUserPasswordResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xd4\x02\n" +
	"\vClusterNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.ztap.api.v1.ClusterNode.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\rClusterStatus\x120\n" +
	"\x06leader\x18\x01 \x01(\v2\x18.ztap.api.v1.ClusterNodeR\x06leader\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12.\n" +
	"\x05nodes\x18\x03 \x03(\v2\x18.ztap.api.v1.ClusterNodeR\x05nodes\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vtotal_nodes\x18\x05 \x01(\x05R\n" +
	"totalNodes\"N\n" +
	"\x18GetClusterStatusResponse\x122\n" +
	"\x06status\x18\x01 \x01(\v2\x1a.ztap.api.v1.ClusterStatusR\x06status\"C\n" +
	"\x11ListNodesResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.ztap.api.v1.ClusterNodeR\x05nodes\"C\n" +
	"\x13RegisterNodeRequest\x12,\n" +
	"\x04node\x18\x01 \x01(\v2\x18.ztap.api.v1.ClusterNodeR\x04node\"D\n" +
	"\x14RegisterNodeResponse\x12,\n" +
	"\x04node\x18\x01 \x01(\v2\x18.ztap.api.v1.ClusterNodeR\x04node\"0\n" +
	"\x15DeregisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"2\n" +
	"\x16DeregisterNodeResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x8c\x01\n" +
	"\vAuthService\x12>\n" +
	"\x05Login\x12\x19.ztap.api.v1.LoginRequest\x1a\x1a.ztap.api.v1.LoginResponse\x12=\n" +
	"\x06WhoAmI\x12\x16.google.protobuf.Empty\x1a\x1b.ztap.api.v1.WhoAmIResponse2Q\n" +
	"\rStatusService\x12@\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1b.ztap.api.v1.StatusResponse2\xfd\x01\n" +
	"\x12EnforcementService\x12K\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a&.ztap.api.v1.EnforcementStatusResponse\x12T\n" +
	"\x05Start\x12$.ztap.api.v1.EnforcementStartRequest\x1a%.ztap.api.v1.EnforcementStartResponse\x12D\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a$.ztap.api.v1.EnforcementStopResponse2J\n" +
	"\fFlowsService\x12:\n" +
	"\x06Stream\x12\x16.google.protobuf.Empty\x1a\x16.ztap.api.v1.FlowEvent0\x012\xfa\x04\n" +
	"\rPolicyService\x12S\n" +
	"\fListPolicies\x12 .ztap.api.v1.ListPoliciesRequest\x1a!.ztap.api.v1.ListPoliciesResponse\x12J\n" +
	"\tGetPolicy\x12\x1d.ztap.api.v1.GetPolicyRequest\x1a\x1e.ztap.api.v1.GetPolicyResponse\x12J\n" +
	"\tPutPolicy\x12\x1d.ztap.api.v1.PutPolicyRequest\x1a\x1e.ztap.api.v1.PutPolicyResponse\x12S\n" +
	"\fDeletePolicy\x12 .ztap.api.v1.DeletePolicyRequest\x1a!.ztap.api.v1.DeletePolicyResponse\x12h\n" +
	"\x13ListPolicyRevisions\x12'.ztap.api.v1.ListPolicyRevisionsRequest\x1a(.ztap.api.v1.ListPolicyRevisionsResponse\x12b\n" +
	"\x11GetPolicyRevision\x12%.ztap.api.v1.GetPolicyRevisionRequest\x1a&.ztap.api.v1.GetPolicyRevisionResponse\x12Y\n" +
	"\x0eRollbackPolicy\x12\".ztap.api.v1.RollbackPolicyRequest\x1a#.ztap.api.v1.RollbackPolicyResponse2\xd9\x03\n" +
	"\fUsersService\x12C\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x1e.ztap.api.v1.ListUsersResponse\x129\n" +
	"\aGetUser\x12\x1b.ztap.api.v1.GetUserRequest\x1a\x11.ztap.api.v1.User\x12M\n" +
	"\n" +
	"CreateUser\x12\x1e.ztap.api.v1.CreateUserRequest\x1a\x1f.ztap.api.v1.CreateUserResponse\x12M\n" +
	"\n" +
	"UpdateUser\x12\x1e.ztap.api.v1.UpdateUserRequest\x1a\x1f.ztap.api.v1.UpdateUserResponse\x12\\\n" +
	"\x0fSetUserPassword\x12#.ztap.api.v1.SetUserPasswordRequest\x1a$.ztap.api.v1.SetUserPasswordResponse\x12M\n" +
	"\n" +
	"DeleteUser\x12\x1e.ztap.api.v1.DeleteUserRequest\x1a\x1f.ztap.api.v1.DeleteUserResponse2\xd8\x02\n" +
	"\x0eClusterService\x12Q\n" +
	"\x10GetClusterStatus\x12\x16.google.protobuf.Empty\x1a%.ztap.api.v1.GetClusterStatusResponse\x12C\n" +
	"\tListNodes\x12\x16.google.protobuf.Empty\x1a\x1e.ztap.api.v1.ListNodesResponse\x12S\n" +
	"\fRegisterNode\x12 .ztap.api.v1.RegisterNodeRequest\x1a!.ztap.api.v1.RegisterNodeResponse\x12Y\n" +
	"\x0eDeregisterNode\x12\".ztap.api.v1.DeregisterNodeRequest\x1a#.ztap.api.v1.DeregisterNodeResponseB\x1eZ\x1cztap/proto/ztap/api/v1;apiv1b\x06proto3"

var (
	file_proto_ztap_api_v1_api_proto_rawDescOnce sync.Once
	file_proto_ztap_api_v1_api_proto_rawDescData []byte
)

func file_proto_ztap_api_v1_api_proto_rawDescGZIP() []byte {
	file_proto_ztap_api_v1_api_proto_rawDescOnce.Do(func() {
		file_proto_ztap_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ztap_api_v1_api_proto_rawDesc), len(file_proto_ztap_api_v1_api_proto_rawDesc)))
	})
	return file_proto_ztap_api_v1_api_proto_rawDescData
}

var file_proto_ztap_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_ztap_api_v1_api_proto_goTypes = []any{
	(*LoginRequest)(nil),                // 0: ztap.api.v1.LoginRequest
	(*LoginResponse)(nil),               // 1: ztap.api.v1.LoginResponse
	(*WhoAmIResponse)(nil),              // 2: ztap.api.v1.WhoAmIResponse
	(*StatusResponse)(nil),              // 3: ztap.api.v1.StatusResponse
	(*EnforcementStatusResponse)(nil),   // 4: ztap.api.v1.EnforcementStatusResponse
	(*EnforcementStartRequest)(nil),     // 5: ztap.api.v1.EnforcementStartRequest
	(*EnforcementStartResponse)(nil),    // 6: ztap.api.v1.EnforcementStartResponse
	(*EnforcementStopResponse)(nil),     // 7: ztap.api.v1.EnforcementStopResponse
	(*FlowEvent)(nil),                   // 8: ztap.api.v1.FlowEvent
	(*PolicySummary)(nil),               // 9: ztap.api.v1.PolicySummary
	(*Policy)(nil),                      // 10: ztap.api.v1.Policy
	(*PolicyRevision)(nil),              // 11: ztap.api.v1.PolicyRevision
	(*ListPoliciesRequest)(nil),         // 12: ztap.api.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),        // 13: ztap.api.v1.ListPoliciesResponse
	(*GetPolicyRequest)(nil),            // 14: ztap.api.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),           // 15: ztap.api.v1.GetPolicyResponse
	(*PutPolicyRequest)(nil),            // 16: ztap.api.v1.PutPolicyRequest
	(*PutPolicyResponse)(nil),           // 17: ztap.api.v1.PutPolicyResponse
	(*DeletePolicyRequest)(nil),         // 18: ztap.api.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),        // 19: ztap.api.v1.DeletePolicyResponse
	(*ListPolicyRevisionsRequest)(nil),  // 20: ztap.api.v1.ListPolicyRevisionsRequest
	(*ListPolicyRevisionsResponse)(nil), // 21: ztap.api.v1.ListPolicyRevisionsResponse
	(*GetPolicyRevisionRequest)(nil),    // 22: ztap.api.v1.GetPolicyRevisionRequest
	(*GetPolicyRevisionResponse)(nil),   // 23: ztap.api.v1.GetPolicyRevisionResponse
	(*RollbackPolicyRequest)(nil),       // 24: ztap.api.v1.RollbackPolicyRequest
	(*RollbackPolicyResponse)(nil),      // 25: ztap.api.v1.RollbackPolicyResponse
	(*User)(nil),                        // 26: ztap.api.v1.User
	(*ListUsersResponse)(nil),           // 27: ztap.api.v1.ListUsersResponse
	(*GetUserRequest)(nil),              // 28: ztap.api.v1.GetUserRequest
	(*CreateUserRequest)(nil),           // 29: ztap.api.v1.CreateUserRequest
	(*CreateUserResponse)(nil),          // 30: ztap.api.v1.CreateUserResponse
	(*UpdateUserRequest)(nil),           // 31: ztap.api.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),          // 32: ztap.api.v1.UpdateUserResponse
	(*SetUserPasswordRequest)(nil),      // 33: ztap.api.v1.SetUserPasswordRequest
	(*SetUserPasswordResponse)(nil),     // 34: ztap.api.v1.SetUserPasswordResponse
	(*DeleteUserRequest)(nil),           // 35: ztap.api.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),          // 36: ztap.api.v1.DeleteUserResponse
	(*ClusterNode)(nil),                 // 37: ztap.api.v1.ClusterNode
	(*ClusterStatus)(nil),               // 38: ztap.api.v1.ClusterStatus
	(*GetClusterStatusResponse)(nil),    // 39: ztap.api.v1.GetClusterStatusResponse
	(*ListNodesResponse)(nil),           // 40: ztap.api.v1.ListNodesResponse
	(*RegisterNodeRequest)(nil),         // 41: ztap.api.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),        // 42: ztap.api.v1.RegisterNodeResponse
	(*DeregisterNodeRequest)(nil),       // 43: ztap.api.v1.DeregisterNodeRequest
	(*DeregisterNodeResponse)(nil),      // 44: ztap.api.v1.DeregisterNodeResponse
	nil,                                 // 45: ztap.api.v1.ClusterNode.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 46: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 47: google.protobuf.Empty
}
var file_proto_ztap_api_v1_api_proto_depIdxs = []int32{
	46, // 0: ztap.api.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	46, // 1: ztap.api.v1.WhoAmIResponse.expires_at:type_name -> google.protobuf.Timestamp
	46, // 2: ztap.api.v1.FlowEvent.timestamp:type_name -> google.protobuf.Timestamp
	46, // 3: ztap.api.v1.PolicySummary.updated_at:type_name -> google.protobuf.Timestamp
	46, // 4: ztap.api.v1.Policy.updated_at:type_name -> google.protobuf.Timestamp
	46, // 5: ztap.api.v1.PolicyRevision.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: ztap.api.v1.ListPoliciesResponse.policies:type_name -> ztap.api.v1.PolicySummary
	10, // 7: ztap.api.v1.GetPolicyResponse.policy:type_name -> ztap.api.v1.Policy
	11, // 8: ztap.api.v1.ListPolicyRevisionsResponse.revisions:type_name -> ztap.api.v1.PolicyRevision
	11, // 9: ztap.api.v1.GetPolicyRevisionResponse.revision:type_name -> ztap.api.v1.PolicyRevision
	46, // 10: ztap.api.v1.User.created_at:type_name -> google.protobuf.Timestamp
	46, // 11: ztap.api.v1.User.last_login:type_name -> google.protobuf.Timestamp
	26, // 12: ztap.api.v1.ListUsersResponse.users:type_name -> ztap.api.v1.User
	26, // 13: ztap.api.v1.CreateUserResponse.user:type_name -> ztap.api.v1.User
	26, // 14: ztap.api.v1.UpdateUserResponse.user:type_name -> ztap.api.v1.User
	46, // 15: ztap.api.v1.ClusterNode.joined_at:type_name -> google.protobuf.Timestamp
	46, // 16: ztap.api.v1.ClusterNode.last_seen:type_name -> google.protobuf.Timestamp
	45, // 17: ztap.api.v1.ClusterNode.metadata:type_name -> ztap.api.v1.ClusterNode.MetadataEntry
	37, // 18: ztap.api.v1.ClusterStatus.leader:type_name -> ztap.api.v1.ClusterNode
	37, // 19: ztap.api.v1.ClusterStatus.nodes:type_name -> ztap.api.v1.ClusterNode
	46, // 20: ztap.api.v1.ClusterStatus.updated_at:type_name -> google.protobuf.Timestamp
	38, // 21: ztap.api.v1.GetClusterStatusResponse.status:type_name -> ztap.api.v1.ClusterStatus
	37, // 22: ztap.api.v1.ListNodesResponse.nodes:type_name -> ztap.api.v1.ClusterNode
	37, // 23: ztap.api.v1.RegisterNodeRequest.node:type_name -> ztap.api.v1.ClusterNode
	37, // 24: ztap.api.v1.RegisterNodeResponse.node:type_name -> ztap.api.v1.ClusterNode
	0,  // 25: ztap.api.v1.AuthService.Login:input_type -> ztap.api.v1.LoginRequest
	47, // 26: ztap.api.v1.AuthService.WhoAmI:input_type -> google.protobuf.Empty
	47, // 27: ztap.api.v1.StatusService.GetStatus:input_type -> google.protobuf.Empty
	47, // 28: ztap.api.v1.EnforcementService.GetStatus:input_type -> google.protobuf.Empty
	5,  // 29: ztap.api.v1.EnforcementService.Start:input_type -> ztap.api.v1.EnforcementStartRequest
	47, // 30: ztap.api.v1.EnforcementService.Stop:input_type -> google.protobuf.Empty
	47, // 31: ztap.api.v1.FlowsService.Stream:input_type -> google.protobuf.Empty
	12, // 32: ztap.api.v1.PolicyService.ListPolicies:input_type -> ztap.api.v1.ListPoliciesRequest
	14, // 33: ztap.api.v1.PolicyService.GetPolicy:input_type -> ztap.api.v1.GetPolicyRequest
	16, // 34: ztap.api.v1.PolicyService.PutPolicy:input_type -> ztap.api.v1.PutPolicyRequest
	18, // 35: ztap.api.v1.PolicyService.DeletePolicy:input_type -> ztap.api.v1.DeletePolicyRequest
	20, // 36: ztap.api.v1.PolicyService.ListPolicyRevisions:input_type -> ztap.api.v1.ListPolicyRevisionsRequest
	22, // 37: ztap.api.v1.PolicyService.GetPolicyRevision:input_type -> ztap.api.v1.GetPolicyRevisionRequest
	24, // 38: ztap.api.v1.PolicyService.RollbackPolicy:input_type -> ztap.api.v1.RollbackPolicyRequest
	47, // 39: ztap.api.v1.UsersService.ListUsers:input_type -> google.protobuf.Empty
	28, // 40: ztap.api.v1.UsersService.GetUser:input_type -> ztap.api.v1.GetUserRequest
	29, // 41: ztap.api.v1.UsersService.CreateUser:input_type -> ztap.api.v1.CreateUserRequest
	31, // 42: ztap.api.v1.UsersService.UpdateUser:input_type -> ztap.api.v1.UpdateUserRequest
	33, // 43: ztap.api.v1.UsersService.SetUserPassword:input_type -> ztap.api.v1.SetUserPasswordRequest
	35, // 44: ztap.api.v1.UsersService.DeleteUser:input_type -> ztap.api.v1.DeleteUserRequest
	47, // 45: ztap.api.v1.ClusterService.GetClusterStatus:input_type -> google.protobuf.Empty
	47, // 46: ztap.api.v1.ClusterService.ListNodes:input_type -> google.protobuf.Empty
	41, // 47: ztap.api.v1.ClusterService.RegisterNode:input_type -> ztap.api.v1.RegisterNodeRequest
	43, // 48: ztap.api.v1.ClusterService.DeregisterNode:input_type -> ztap.api.v1.DeregisterNodeRequest
	1,  // 49: ztap.api.v1.AuthService.Login:output_type -> ztap.api.v1.LoginResponse
	2,  // 50: ztap.api.v1.AuthService.WhoAmI:output_type -> ztap.api.v1.WhoAmIResponse
	3,  // 51: ztap.api.v1.StatusService.GetStatus:output_type -> ztap.api.v1.StatusResponse
	4,  // 52: ztap.api.v1.EnforcementService.GetStatus:output_type -> ztap.api.v1.EnforcementStatusResponse
	6,  // 53: ztap.api.v1.EnforcementService.Start:output_type -> ztap.api.v1.EnforcementStartResponse
	7,  // 54: ztap.api.v1.EnforcementService.Stop:output_type -> ztap.api.v1.EnforcementStopResponse
	8,  // 55: ztap.api.v1.FlowsService.Stream:output_type -> ztap.api.v1.FlowEvent
	13, // 56: ztap.api.v1.PolicyService.ListPolicies:output_type -> ztap.api.v1.ListPoliciesResponse
	15, // 57: ztap.api.v1.PolicyService.GetPolicy:output_type -> ztap.api.v1.GetPolicyResponse
	17, // 58: ztap.api.v1.PolicyService.PutPolicy:output_type -> ztap.api.v1.PutPolicyResponse
	19, // 59: ztap.api.v1.PolicyService.DeletePolicy:output_type -> ztap.api.v1.DeletePolicyResponse
	21, // 60: ztap.api.v1.PolicyService.ListPolicyRevisions:output_type -> ztap.api.v1.ListPolicyRevisionsResponse
	23, // 61: ztap.api.v1.PolicyService.GetPolicyRevision:output_type -> ztap.api.v1.GetPolicyRevisionResponse
	25, // 62: ztap.api.v1.PolicyService.RollbackPolicy:output_type -> ztap.api.v1.RollbackPolicyResponse
	27, // 63: ztap.api.v1.UsersService.ListUsers:output_type -> ztap.api.v1.ListUsersResponse
	26, // 64: ztap.api.v1.UsersService.GetUser:output_type -> ztap.api.v1.User
	30, // 65: ztap.api.v1.UsersService.CreateUser:output_type -> ztap.api.v1.CreateUserResponse
	32, // 66: ztap.api.v1.UsersService.UpdateUser:output_type -> ztap.api.v1.UpdateUserResponse
	34, // 67: ztap.api.v1.UsersService.SetUserPassword:output_type -> ztap.api.v1.SetUserPasswordResponse
	36, // 68: ztap.api.v1.UsersService.DeleteUser:output_type -> ztap.api.v1.DeleteUserResponse
	39, // 69: ztap.api.v1.ClusterService.GetClusterStatus:output_type -> ztap.api.v1.GetClusterStatusResponse
	40, // 70: ztap.api.v1.ClusterService.ListNodes:output_type -> ztap.api.v1.ListNodesResponse
	42, // 71: ztap.api.v1.ClusterService.RegisterNode:output_type -> ztap.api.v1.RegisterNodeResponse
	44, // 72: ztap.api.v1.ClusterService.DeregisterNode:output_type -> ztap.api.v1.DeregisterNodeResponse
	49, // [49:73] is the sub-list for method output_type
	25, // [25:49] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_ztap_api_v1_api_proto_init() }
func file_proto_ztap_api_v1_api_proto_init() {
	if File_proto_ztap_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ztap_api_v1_api_proto_rawDesc), len(file_proto_ztap_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_proto_ztap_api_v1_api_proto_goTypes,
		DependencyIndexes: file_proto_ztap_api_v1_api_proto_depIdxs,
		MessageInfos:      file_proto_ztap_api_v1_api_proto_msgTypes,
	}.Build()
	File_proto_ztap_api_v1_api_proto = out.File
	file_proto_ztap_api_v1_api_proto_goTypes = nil
	file_proto_ztap_api_v1_api_proto_depIdxs = nil
}
