package ztapoperator




















































































}	}		os.Exit(1)		setupLog.Error(err, "problem running manager")	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {	setupLog.Info("starting manager")	}		os.Exit(1)		setupLog.Error(err, "unable to set up ready check")	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {	}		os.Exit(1)		setupLog.Error(err, "unable to set up health check")	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {	}		os.Exit(1)		setupLog.Error(err, "unable to create controller", "controller", "ZtapNetworkPolicy")	}).SetupWithManager(mgr); err != nil {		Scheme: mgr.GetScheme(),		Client: mgr.GetClient(),	if err = (&controllers.ZtapNetworkPolicyReconciler{	}		os.Exit(1)		setupLog.Error(err, "unable to start manager")	if err != nil {	})		LeaderElectionID:       "ztap-operator-leader-election",		LeaderElection:         enableLeaderElection,		HealthProbeBindAddress: probeAddr,		Port:                   9443,		MetricsBindAddress:     metricsAddr,		Scheme:                 scheme,	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))	flag.Parse()	opts.BindFlags(flag.CommandLine)	}		Development: true,	opts := zap.Options{			"Enabling this will ensure there is only one active controller manager.")		"Enable leader election for controller manager. "+	flag.BoolVar(&enableLeaderElection, "leader-elect", false,	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metric endpoint binds to.")	var probeAddr string	var enableLeaderElection bool	var metricsAddr stringfunc main() {}	utilruntime.Must(ztapv1alpha1.AddToScheme(scheme))	utilruntime.Must(clientgoscheme.AddToScheme(scheme))func init() {)	setupLog = ctrl.Log.WithName("setup")	scheme   = runtime.NewScheme()var ()	"ztap/pkg/operator/controllers"	ztapv1alpha1 "ztap/pkg/operator/api/v1alpha1"	"sigs.k8s.io/controller-runtime/pkg/log/zap"	"sigs.k8s.io/controller-runtime/pkg/healthz"	ctrl "sigs.k8s.io/controller-runtime"	clientgoscheme "k8s.io/client-go/kubernetes/scheme"	utilruntime "k8s.io/apimachinery/pkg/util/runtime"	"k8s.io/apimachinery/pkg/runtime"	_ "k8s.io/client-go/plugin/pkg/client/auth"	// to ensure that exec-entrypoint and run can make use of them.	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)	"os"	"flag"import (package main