package v1alpha1
package v1alpha1












































































































}	SchemeBuilder.Register(&ZtapNetworkPolicy{}, &ZtapNetworkPolicyList{})func init() {}	Items           []ZtapNetworkPolicy `json:"items"`	metav1.ListMeta `json:"metadata,omitempty"`	metav1.TypeMeta `json:",inline"`type ZtapNetworkPolicyList struct {// ZtapNetworkPolicyList contains a list of ZtapNetworkPolicy// +kubebuilder:object:root=true}	Status ZtapNetworkPolicyStatus `json:"status,omitempty"`	Spec   ZtapNetworkPolicySpec   `json:"spec,omitempty"`	metav1.ObjectMeta `json:"metadata,omitempty"`	metav1.TypeMeta   `json:",inline"`type ZtapNetworkPolicy struct {// ZtapNetworkPolicy is the Schema for the ztapnetworkpolicies API// +kubebuilder:resource:shortName=ztnp// +kubebuilder:subresource:status// +kubebuilder:object:root=true}	LastPublishedVersion int64 `json:"lastPublishedVersion,omitempty"`	// LastPublishedVersion is the version of the policy published to the distribution store.	Conditions []metav1.Condition `json:"conditions,omitempty"`	// Conditions represent the latest available observations of an object's state.	ObservedGeneration int64 `json:"observedGeneration,omitempty"`	// ObservedGeneration is the last generation of the resource that was reconciled.type ZtapNetworkPolicyStatus struct {// ZtapNetworkPolicyStatus defines the observed state of ZtapNetworkPolicy}	Ingress []IngressRule `json:"ingress,omitempty"`	// +optional	// Ingress is a list of ingress rules to be applied to the selected pods.	Egress []EgressRule `json:"egress,omitempty"`	// +optional	// Egress is a list of egress rules to be applied to the selected pods.	PodSelector PodSelectorSpec `json:"podSelector"`	// PodSelector selects the pods to which this NetworkPolicy applies.type ZtapNetworkPolicySpec struct {// ZtapNetworkPolicySpec defines the desired state of ZtapNetworkPolicy}	Ports []PortSpec `json:"ports"`	// Ports is the list of ports for this rule.	From IngressSource `json:"from"`	// From is the list of sources for this rule.type IngressRule struct {// IngressRule defines an inbound traffic rule.}	IPBlock *IPBlockSpec `json:"ipBlock,omitempty"`	// +optional	// IPBlock selects IP ranges as sources.	PodSelector *PodSelectorSpec `json:"podSelector,omitempty"`	// +optional	// PodSelector selects pods as sources.type IngressSource struct {// IngressSource defines the source for ingress rules.}	Ports []PortSpec `json:"ports"`	// Ports is the list of ports for this rule.	To EgressTarget `json:"to"`	// To is the list of destinations for this rule.type EgressRule struct {// EgressRule defines an outbound traffic rule.}	IPBlock *IPBlockSpec `json:"ipBlock,omitempty"`	// +optional	// IPBlock selects IP ranges as destinations.	PodSelector *PodSelectorSpec `json:"podSelector,omitempty"`	// +optional	// PodSelector selects pods as destinations.type EgressTarget struct {// EgressTarget defines the destination for egress rules.}	CIDR string `json:"cidr"`	// CIDR is the network CIDR (e.g. 10.0.0.0/8).type IPBlockSpec struct {// IPBlockSpec defines CIDR-based IP selection.}	MatchLabels map[string]string `json:"matchLabels"`	// MatchLabels is a map of {key,value} pairs.type PodSelectorSpec struct {// PodSelectorSpec defines label-based pod selection.}	Port int `json:"port"`	// Port is the port number (1-65535).	Protocol string `json:"protocol"`	// Protocol is the network protocol (TCP, UDP, or ICMP).type PortSpec struct {// PortSpec defines a protocol and port combination for network rules.)	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"import (